sudo: required
services:
  - docker

before_install:
  - docker build -t throdines/docker-react -f Dockerfile.dev .

script:
  - docker run throdines/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "thiago"
  env: "Thiago-env"
  bucket_name: "elasticbeanstalk-us-west-2-769177069788"
  bucket_path: "thiago"
  on:
      branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY
